/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiError,
  CreateTicketRequestBody,
  CreateUserForgotPasswordRequestBody,
  CreateUserRequestBody,
  RefreshTokenRestRequestBody,
  RequestLoginRequestBody,
  ResponseLogin,
  ResponseTicket,
  ResponseTicketPaginated,
  ResponseToCreateUserForgotPassword,
  ResponseToUpdateUserForgotPassword,
  ResponseUser,
  UpdateTicketRequestBody,
  UpdateUserForgotPasswordRequestBody,
  UpdateUserRequestBody,
} from "./model";

/**
 * Endpoint to user login using email and password.
 * @summary User login.
 */
export type loginRestControllerExecuteResponse200 = {
  data: ResponseLogin;
  status: 200;
};

export type loginRestControllerExecuteResponse400 = {
  data: void;
  status: 400;
};

export type loginRestControllerExecuteResponse401 = {
  data: void;
  status: 401;
};

export type loginRestControllerExecuteResponse422 = {
  data: void;
  status: 422;
};

export type loginRestControllerExecuteResponseSuccess = loginRestControllerExecuteResponse200 & {
  headers: Headers;
};
export type loginRestControllerExecuteResponseError = (
  | loginRestControllerExecuteResponse400
  | loginRestControllerExecuteResponse401
  | loginRestControllerExecuteResponse422
) & {
  headers: Headers;
};

export type loginRestControllerExecuteResponse =
  | loginRestControllerExecuteResponseSuccess
  | loginRestControllerExecuteResponseError;

export const getLoginRestControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/auth/login`;
};

export const loginRestControllerExecute = async (
  requestLoginRequestBody: RequestLoginRequestBody,
  options?: RequestInit,
): Promise<loginRestControllerExecuteResponse> => {
  const res = await fetch(getLoginRestControllerExecuteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(requestLoginRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginRestControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as loginRestControllerExecuteResponse;
};

export const getLoginRestControllerExecuteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginRestControllerExecute>>,
    TError,
    { data: RequestLoginRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginRestControllerExecute>>,
  TError,
  { data: RequestLoginRequestBody },
  TContext
> => {
  const mutationKey = ["loginRestControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginRestControllerExecute>>,
    { data: RequestLoginRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return loginRestControllerExecute(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginRestControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginRestControllerExecute>>
>;
export type LoginRestControllerExecuteMutationBody = RequestLoginRequestBody;
export type LoginRestControllerExecuteMutationError = void;

/**
 * @summary User login.
 */
export const useLoginRestControllerExecute = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginRestControllerExecute>>,
      TError,
      { data: RequestLoginRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginRestControllerExecute>>,
  TError,
  { data: RequestLoginRequestBody },
  TContext
> => {
  const mutationOptions = getLoginRestControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Endpoint to user get a new access token using a expired access token.
 * @summary User get a new access token.
 */
export type refreshTokenRestControllerExecuteResponse200 = {
  data: ResponseLogin;
  status: 200;
};

export type refreshTokenRestControllerExecuteResponse400 = {
  data: void;
  status: 400;
};

export type refreshTokenRestControllerExecuteResponse401 = {
  data: void;
  status: 401;
};

export type refreshTokenRestControllerExecuteResponse422 = {
  data: void;
  status: 422;
};

export type refreshTokenRestControllerExecuteResponseSuccess =
  refreshTokenRestControllerExecuteResponse200 & {
    headers: Headers;
  };
export type refreshTokenRestControllerExecuteResponseError = (
  | refreshTokenRestControllerExecuteResponse400
  | refreshTokenRestControllerExecuteResponse401
  | refreshTokenRestControllerExecuteResponse422
) & {
  headers: Headers;
};

export type refreshTokenRestControllerExecuteResponse =
  | refreshTokenRestControllerExecuteResponseSuccess
  | refreshTokenRestControllerExecuteResponseError;

export const getRefreshTokenRestControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/auth/refresh-token`;
};

export const refreshTokenRestControllerExecute = async (
  refreshTokenRestRequestBody: RefreshTokenRestRequestBody,
  options?: RequestInit,
): Promise<refreshTokenRestControllerExecuteResponse> => {
  const res = await fetch(getRefreshTokenRestControllerExecuteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(refreshTokenRestRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refreshTokenRestControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as refreshTokenRestControllerExecuteResponse;
};

export const getRefreshTokenRestControllerExecuteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>,
    TError,
    { data: RefreshTokenRestRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>,
  TError,
  { data: RefreshTokenRestRequestBody },
  TContext
> => {
  const mutationKey = ["refreshTokenRestControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>,
    { data: RefreshTokenRestRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return refreshTokenRestControllerExecute(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokenRestControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>
>;
export type RefreshTokenRestControllerExecuteMutationBody = RefreshTokenRestRequestBody;
export type RefreshTokenRestControllerExecuteMutationError = void;

/**
 * @summary User get a new access token.
 */
export const useRefreshTokenRestControllerExecute = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>,
      TError,
      { data: RefreshTokenRestRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof refreshTokenRestControllerExecute>>,
  TError,
  { data: RefreshTokenRestRequestBody },
  TContext
> => {
  const mutationOptions = getRefreshTokenRestControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Endpoint to create a new forgot password.
 * @summary User create forgot password.
 */
export type createForgotPasswordRestControllerExecuteResponse200 = {
  data: ResponseToCreateUserForgotPassword;
  status: 200;
};

export type createForgotPasswordRestControllerExecuteResponse400 = {
  data: void;
  status: 400;
};

export type createForgotPasswordRestControllerExecuteResponse401 = {
  data: void;
  status: 401;
};

export type createForgotPasswordRestControllerExecuteResponse422 = {
  data: void;
  status: 422;
};

export type createForgotPasswordRestControllerExecuteResponseSuccess =
  createForgotPasswordRestControllerExecuteResponse200 & {
    headers: Headers;
  };
export type createForgotPasswordRestControllerExecuteResponseError = (
  | createForgotPasswordRestControllerExecuteResponse400
  | createForgotPasswordRestControllerExecuteResponse401
  | createForgotPasswordRestControllerExecuteResponse422
) & {
  headers: Headers;
};

export type createForgotPasswordRestControllerExecuteResponse =
  | createForgotPasswordRestControllerExecuteResponseSuccess
  | createForgotPasswordRestControllerExecuteResponseError;

export const getCreateForgotPasswordRestControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/auth/forgot-password`;
};

export const createForgotPasswordRestControllerExecute = async (
  createUserForgotPasswordRequestBody: CreateUserForgotPasswordRequestBody,
  options?: RequestInit,
): Promise<createForgotPasswordRestControllerExecuteResponse> => {
  const res = await fetch(getCreateForgotPasswordRestControllerExecuteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserForgotPasswordRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createForgotPasswordRestControllerExecuteResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createForgotPasswordRestControllerExecuteResponse;
};

export const getCreateForgotPasswordRestControllerExecuteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>,
    TError,
    { data: CreateUserForgotPasswordRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>,
  TError,
  { data: CreateUserForgotPasswordRequestBody },
  TContext
> => {
  const mutationKey = ["createForgotPasswordRestControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>,
    { data: CreateUserForgotPasswordRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return createForgotPasswordRestControllerExecute(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateForgotPasswordRestControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>
>;
export type CreateForgotPasswordRestControllerExecuteMutationBody =
  CreateUserForgotPasswordRequestBody;
export type CreateForgotPasswordRestControllerExecuteMutationError = void;

/**
 * @summary User create forgot password.
 */
export const useCreateForgotPasswordRestControllerExecute = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>,
      TError,
      { data: CreateUserForgotPasswordRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createForgotPasswordRestControllerExecute>>,
  TError,
  { data: CreateUserForgotPasswordRequestBody },
  TContext
> => {
  const mutationOptions = getCreateForgotPasswordRestControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Endpoint to update forgot password.
 * @summary User update forgot password.
 */
export type updateForgotPasswordRestControllerExecuteResponse200 = {
  data: ResponseToUpdateUserForgotPassword;
  status: 200;
};

export type updateForgotPasswordRestControllerExecuteResponse400 = {
  data: void;
  status: 400;
};

export type updateForgotPasswordRestControllerExecuteResponse401 = {
  data: void;
  status: 401;
};

export type updateForgotPasswordRestControllerExecuteResponse422 = {
  data: void;
  status: 422;
};

export type updateForgotPasswordRestControllerExecuteResponseSuccess =
  updateForgotPasswordRestControllerExecuteResponse200 & {
    headers: Headers;
  };
export type updateForgotPasswordRestControllerExecuteResponseError = (
  | updateForgotPasswordRestControllerExecuteResponse400
  | updateForgotPasswordRestControllerExecuteResponse401
  | updateForgotPasswordRestControllerExecuteResponse422
) & {
  headers: Headers;
};

export type updateForgotPasswordRestControllerExecuteResponse =
  | updateForgotPasswordRestControllerExecuteResponseSuccess
  | updateForgotPasswordRestControllerExecuteResponseError;

export const getUpdateForgotPasswordRestControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/auth/forgot-password/${id}`;
};

export const updateForgotPasswordRestControllerExecute = async (
  id: unknown,
  updateUserForgotPasswordRequestBody: UpdateUserForgotPasswordRequestBody,
  options?: RequestInit,
): Promise<updateForgotPasswordRestControllerExecuteResponse> => {
  const res = await fetch(getUpdateForgotPasswordRestControllerExecuteUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserForgotPasswordRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateForgotPasswordRestControllerExecuteResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateForgotPasswordRestControllerExecuteResponse;
};

export const getUpdateForgotPasswordRestControllerExecuteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>,
    TError,
    { id: unknown; data: UpdateUserForgotPasswordRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>,
  TError,
  { id: unknown; data: UpdateUserForgotPasswordRequestBody },
  TContext
> => {
  const mutationKey = ["updateForgotPasswordRestControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>,
    { id: unknown; data: UpdateUserForgotPasswordRequestBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateForgotPasswordRestControllerExecute(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateForgotPasswordRestControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>
>;
export type UpdateForgotPasswordRestControllerExecuteMutationBody =
  UpdateUserForgotPasswordRequestBody;
export type UpdateForgotPasswordRestControllerExecuteMutationError = void;

/**
 * @summary User update forgot password.
 */
export const useUpdateForgotPasswordRestControllerExecute = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>,
      TError,
      { id: unknown; data: UpdateUserForgotPasswordRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateForgotPasswordRestControllerExecute>>,
  TError,
  { id: unknown; data: UpdateUserForgotPasswordRequestBody },
  TContext
> => {
  const mutationOptions = getUpdateForgotPasswordRestControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Create a new user
 */
export type createUserControllerExecuteResponse200 = {
  data: ResponseUser;
  status: 200;
};

export type createUserControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type createUserControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type createUserControllerExecuteResponseSuccess = createUserControllerExecuteResponse200 & {
  headers: Headers;
};
export type createUserControllerExecuteResponseError = (
  | createUserControllerExecuteResponse400
  | createUserControllerExecuteResponse500
) & {
  headers: Headers;
};

export type createUserControllerExecuteResponse =
  | createUserControllerExecuteResponseSuccess
  | createUserControllerExecuteResponseError;

export const getCreateUserControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users`;
};

export const createUserControllerExecute = async (
  createUserRequestBody: CreateUserRequestBody,
  options?: RequestInit,
): Promise<createUserControllerExecuteResponse> => {
  const res = await fetch(getCreateUserControllerExecuteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createUserControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createUserControllerExecuteResponse;
};

export const getCreateUserControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUserControllerExecute>>,
    TError,
    { data: CreateUserRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUserControllerExecute>>,
  TError,
  { data: CreateUserRequestBody },
  TContext
> => {
  const mutationKey = ["createUserControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUserControllerExecute>>,
    { data: CreateUserRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return createUserControllerExecute(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUserControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUserControllerExecute>>
>;
export type CreateUserControllerExecuteMutationBody = CreateUserRequestBody;
export type CreateUserControllerExecuteMutationError = ApiError;

/**
 * @summary Create a new user
 */
export const useCreateUserControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUserControllerExecute>>,
      TError,
      { data: CreateUserRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createUserControllerExecute>>,
  TError,
  { data: CreateUserRequestBody },
  TContext
> => {
  const mutationOptions = getCreateUserControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * The user ID must be provided
 * @summary Performs a soft delete operation
 */
export type deleteUserControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type deleteUserControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type deleteUserControllerExecuteResponseSuccess = deleteUserControllerExecuteResponse200 & {
  headers: Headers;
};
export type deleteUserControllerExecuteResponseError = deleteUserControllerExecuteResponse500 & {
  headers: Headers;
};

export type deleteUserControllerExecuteResponse =
  | deleteUserControllerExecuteResponseSuccess
  | deleteUserControllerExecuteResponseError;

export const getDeleteUserControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users/${id}`;
};

export const deleteUserControllerExecute = async (
  id: unknown,
  options?: RequestInit,
): Promise<deleteUserControllerExecuteResponse> => {
  const res = await fetch(getDeleteUserControllerExecuteUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as deleteUserControllerExecuteResponse;
};

export const getDeleteUserControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserControllerExecute>>,
    TError,
    { id: unknown },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationKey = ["deleteUserControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserControllerExecute>>,
    { id: unknown }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserControllerExecute(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserControllerExecute>>
>;

export type DeleteUserControllerExecuteMutationError = ApiError;

/**
 * @summary Performs a soft delete operation
 */
export const useDeleteUserControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserControllerExecute>>,
      TError,
      { id: unknown },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationOptions = getDeleteUserControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Retrieve a user by their unique ID
 * @summary Get user by ID
 */
export type getUserByIdControllerExecuteResponse200 = {
  data: ResponseUser;
  status: 200;
};

export type getUserByIdControllerExecuteResponse204 = {
  data: void;
  status: 204;
};

export type getUserByIdControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type getUserByIdControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getUserByIdControllerExecuteResponseSuccess = (
  | getUserByIdControllerExecuteResponse200
  | getUserByIdControllerExecuteResponse204
) & {
  headers: Headers;
};
export type getUserByIdControllerExecuteResponseError = (
  | getUserByIdControllerExecuteResponse400
  | getUserByIdControllerExecuteResponse500
) & {
  headers: Headers;
};

export type getUserByIdControllerExecuteResponse =
  | getUserByIdControllerExecuteResponseSuccess
  | getUserByIdControllerExecuteResponseError;

export const getGetUserByIdControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users/${id}`;
};

export const getUserByIdControllerExecute = async (
  id: unknown,
  options?: RequestInit,
): Promise<getUserByIdControllerExecuteResponse> => {
  const res = await fetch(getGetUserByIdControllerExecuteUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByIdControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUserByIdControllerExecuteResponse;
};

export const getGetUserByIdControllerExecuteQueryKey = (id?: unknown) => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/users/${id}`] as const;
};

export const getGetUserByIdControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdControllerExecuteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByIdControllerExecute>>> = ({
    signal,
  }) => getUserByIdControllerExecute(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByIdControllerExecute>>
>;
export type GetUserByIdControllerExecuteQueryError = ApiError;

export function useGetUserByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByIdControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByIdControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get user by ID
 */

export function useGetUserByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserByIdControllerExecuteQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a user's details by their unique ID
 * @summary Update user by ID
 */
export type updateUserByIdControllerExecuteResponse200 = {
  data: ResponseUser;
  status: 200;
};

export type updateUserByIdControllerExecuteResponse204 = {
  data: void;
  status: 204;
};

export type updateUserByIdControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type updateUserByIdControllerExecuteResponse404 = {
  data: void;
  status: 404;
};

export type updateUserByIdControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type updateUserByIdControllerExecuteResponseSuccess = (
  | updateUserByIdControllerExecuteResponse200
  | updateUserByIdControllerExecuteResponse204
) & {
  headers: Headers;
};
export type updateUserByIdControllerExecuteResponseError = (
  | updateUserByIdControllerExecuteResponse400
  | updateUserByIdControllerExecuteResponse404
  | updateUserByIdControllerExecuteResponse500
) & {
  headers: Headers;
};

export type updateUserByIdControllerExecuteResponse =
  | updateUserByIdControllerExecuteResponseSuccess
  | updateUserByIdControllerExecuteResponseError;

export const getUpdateUserByIdControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users/${id}`;
};

export const updateUserByIdControllerExecute = async (
  id: unknown,
  updateUserRequestBody: UpdateUserRequestBody,
  options?: RequestInit,
): Promise<updateUserByIdControllerExecuteResponse> => {
  const res = await fetch(getUpdateUserByIdControllerExecuteUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserByIdControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateUserByIdControllerExecuteResponse;
};

export const getUpdateUserByIdControllerExecuteMutationOptions = <
  TError = ApiError | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserByIdControllerExecute>>,
    TError,
    { id: unknown; data: UpdateUserRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserByIdControllerExecute>>,
  TError,
  { id: unknown; data: UpdateUserRequestBody },
  TContext
> => {
  const mutationKey = ["updateUserByIdControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserByIdControllerExecute>>,
    { id: unknown; data: UpdateUserRequestBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUserByIdControllerExecute(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserByIdControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserByIdControllerExecute>>
>;
export type UpdateUserByIdControllerExecuteMutationBody = UpdateUserRequestBody;
export type UpdateUserByIdControllerExecuteMutationError = ApiError | void;

/**
 * @summary Update user by ID
 */
export const useUpdateUserByIdControllerExecute = <TError = ApiError | void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserByIdControllerExecute>>,
      TError,
      { id: unknown; data: UpdateUserRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserByIdControllerExecute>>,
  TError,
  { id: unknown; data: UpdateUserRequestBody },
  TContext
> => {
  const mutationOptions = getUpdateUserByIdControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Retrieve a user by their email address.
 * @summary Get user by email
 */
export type getUserByEmailControllerExecuteResponse200 = {
  data: ResponseUser;
  status: 200;
};

export type getUserByEmailControllerExecuteResponse204 = {
  data: void;
  status: 204;
};

export type getUserByEmailControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type getUserByEmailControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getUserByEmailControllerExecuteResponseSuccess = (
  | getUserByEmailControllerExecuteResponse200
  | getUserByEmailControllerExecuteResponse204
) & {
  headers: Headers;
};
export type getUserByEmailControllerExecuteResponseError = (
  | getUserByEmailControllerExecuteResponse400
  | getUserByEmailControllerExecuteResponse500
) & {
  headers: Headers;
};

export type getUserByEmailControllerExecuteResponse =
  | getUserByEmailControllerExecuteResponseSuccess
  | getUserByEmailControllerExecuteResponseError;

export const getGetUserByEmailControllerExecuteUrl = (email: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users/by-email/${email}`;
};

export const getUserByEmailControllerExecute = async (
  email: unknown,
  options?: RequestInit,
): Promise<getUserByEmailControllerExecuteResponse> => {
  const res = await fetch(getGetUserByEmailControllerExecuteUrl(email), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByEmailControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserByEmailControllerExecuteResponse;
};

export const getGetUserByEmailControllerExecuteQueryKey = (email?: unknown) => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/users/by-email/${email}`] as const;
};

export const getGetUserByEmailControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
  TError = ApiError,
>(
  email: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserByEmailControllerExecuteQueryKey(email);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>> = ({
    signal,
  }) => getUserByEmailControllerExecute(email, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!email, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByEmailControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByEmailControllerExecute>>
>;
export type GetUserByEmailControllerExecuteQueryError = ApiError;

export function useGetUserByEmailControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
  TError = ApiError,
>(
  email: unknown,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getUserByEmailControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByEmailControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
  TError = ApiError,
>(
  email: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getUserByEmailControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserByEmailControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
  TError = ApiError,
>(
  email: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get user by email
 */

export function useGetUserByEmailControllerExecute<
  TData = Awaited<ReturnType<typeof getUserByEmailControllerExecute>>,
  TError = ApiError,
>(
  email: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserByEmailControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserByEmailControllerExecuteQueryOptions(email, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * This is intended for testing purposes only. This endpoint is disabled in production.
 * @summary Performs a hard delete operation
 */
export type hardDeleteUserControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type hardDeleteUserControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type hardDeleteUserControllerExecuteResponseSuccess =
  hardDeleteUserControllerExecuteResponse200 & {
    headers: Headers;
  };
export type hardDeleteUserControllerExecuteResponseError =
  hardDeleteUserControllerExecuteResponse500 & {
    headers: Headers;
  };

export type hardDeleteUserControllerExecuteResponse =
  | hardDeleteUserControllerExecuteResponseSuccess
  | hardDeleteUserControllerExecuteResponseError;

export const getHardDeleteUserControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/users/testing/${id}`;
};

export const hardDeleteUserControllerExecute = async (
  id: unknown,
  options?: RequestInit,
): Promise<hardDeleteUserControllerExecuteResponse> => {
  const res = await fetch(getHardDeleteUserControllerExecuteUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: hardDeleteUserControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as hardDeleteUserControllerExecuteResponse;
};

export const getHardDeleteUserControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>,
    TError,
    { id: unknown },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationKey = ["hardDeleteUserControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>,
    { id: unknown }
  > = (props) => {
    const { id } = props ?? {};

    return hardDeleteUserControllerExecute(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HardDeleteUserControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>
>;

export type HardDeleteUserControllerExecuteMutationError = ApiError;

/**
 * @summary Performs a hard delete operation
 */
export const useHardDeleteUserControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>,
      TError,
      { id: unknown },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof hardDeleteUserControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationOptions = getHardDeleteUserControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Retrieve chat mock data
 * @summary Get chat data
 */
export type getChatControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type getChatControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getChatControllerExecuteResponseSuccess = getChatControllerExecuteResponse200 & {
  headers: Headers;
};
export type getChatControllerExecuteResponseError = getChatControllerExecuteResponse500 & {
  headers: Headers;
};

export type getChatControllerExecuteResponse =
  | getChatControllerExecuteResponseSuccess
  | getChatControllerExecuteResponseError;

export const getGetChatControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/chat`;
};

export const getChatControllerExecute = async (
  options?: RequestInit,
): Promise<getChatControllerExecuteResponse> => {
  const res = await fetch(getGetChatControllerExecuteUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChatControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getChatControllerExecuteResponse;
};

export const getGetChatControllerExecuteQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/chat`] as const;
};

export const getGetChatControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatControllerExecute>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getChatControllerExecute>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChatControllerExecuteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatControllerExecute>>> = ({
    signal,
  }) => getChatControllerExecute({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChatControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatControllerExecute>>
>;
export type GetChatControllerExecuteQueryError = ApiError;

export function useGetChatControllerExecute<
  TData = Awaited<ReturnType<typeof getChatControllerExecute>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChatControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getChatControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatControllerExecute<
  TData = Awaited<ReturnType<typeof getChatControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChatControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getChatControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatControllerExecute<
  TData = Awaited<ReturnType<typeof getChatControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChatControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get chat data
 */

export function useGetChatControllerExecute<
  TData = Awaited<ReturnType<typeof getChatControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChatControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChatControllerExecuteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieve dashboard mock data
 * @summary Get dashboard data
 */
export type getDashboardControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type getDashboardControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getDashboardControllerExecuteResponseSuccess =
  getDashboardControllerExecuteResponse200 & {
    headers: Headers;
  };
export type getDashboardControllerExecuteResponseError =
  getDashboardControllerExecuteResponse500 & {
    headers: Headers;
  };

export type getDashboardControllerExecuteResponse =
  | getDashboardControllerExecuteResponseSuccess
  | getDashboardControllerExecuteResponseError;

export const getGetDashboardControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/dashboard`;
};

export const getDashboardControllerExecute = async (
  options?: RequestInit,
): Promise<getDashboardControllerExecuteResponse> => {
  const res = await fetch(getGetDashboardControllerExecuteUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDashboardControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getDashboardControllerExecuteResponse;
};

export const getGetDashboardControllerExecuteQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/dashboard`] as const;
};

export const getGetDashboardControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardControllerExecute>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDashboardControllerExecute>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardControllerExecuteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardControllerExecute>>> = ({
    signal,
  }) => getDashboardControllerExecute({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardControllerExecute>>
>;
export type GetDashboardControllerExecuteQueryError = ApiError;

export function useGetDashboardControllerExecute<
  TData = Awaited<ReturnType<typeof getDashboardControllerExecute>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDashboardControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getDashboardControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardControllerExecute<
  TData = Awaited<ReturnType<typeof getDashboardControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDashboardControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getDashboardControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardControllerExecute<
  TData = Awaited<ReturnType<typeof getDashboardControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDashboardControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get dashboard data
 */

export function useGetDashboardControllerExecute<
  TData = Awaited<ReturnType<typeof getDashboardControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDashboardControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDashboardControllerExecuteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieve simulador planos mock data
 * @summary Get simulador planos data
 */
export type getSimuladorPlanosControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type getSimuladorPlanosControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getSimuladorPlanosControllerExecuteResponseSuccess =
  getSimuladorPlanosControllerExecuteResponse200 & {
    headers: Headers;
  };
export type getSimuladorPlanosControllerExecuteResponseError =
  getSimuladorPlanosControllerExecuteResponse500 & {
    headers: Headers;
  };

export type getSimuladorPlanosControllerExecuteResponse =
  | getSimuladorPlanosControllerExecuteResponseSuccess
  | getSimuladorPlanosControllerExecuteResponseError;

export const getGetSimuladorPlanosControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/simulador-planos`;
};

export const getSimuladorPlanosControllerExecute = async (
  options?: RequestInit,
): Promise<getSimuladorPlanosControllerExecuteResponse> => {
  const res = await fetch(getGetSimuladorPlanosControllerExecuteUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSimuladorPlanosControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getSimuladorPlanosControllerExecuteResponse;
};

export const getGetSimuladorPlanosControllerExecuteQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/nortus-v1/simulador-planos`] as const;
};

export const getGetSimuladorPlanosControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSimuladorPlanosControllerExecuteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>> = ({
    signal,
  }) => getSimuladorPlanosControllerExecute({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSimuladorPlanosControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>
>;
export type GetSimuladorPlanosControllerExecuteQueryError = ApiError;

export function useGetSimuladorPlanosControllerExecute<
  TData = Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSimuladorPlanosControllerExecute<
  TData = Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSimuladorPlanosControllerExecute<
  TData = Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get simulador planos data
 */

export function useGetSimuladorPlanosControllerExecute<
  TData = Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimuladorPlanosControllerExecute>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSimuladorPlanosControllerExecuteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new ticket
 */
export type createTicketControllerExecuteResponse200 = {
  data: ResponseTicket;
  status: 200;
};

export type createTicketControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type createTicketControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type createTicketControllerExecuteResponseSuccess =
  createTicketControllerExecuteResponse200 & {
    headers: Headers;
  };
export type createTicketControllerExecuteResponseError = (
  | createTicketControllerExecuteResponse400
  | createTicketControllerExecuteResponse500
) & {
  headers: Headers;
};

export type createTicketControllerExecuteResponse =
  | createTicketControllerExecuteResponseSuccess
  | createTicketControllerExecuteResponseError;

export const getCreateTicketControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/tickets`;
};

export const createTicketControllerExecute = async (
  createTicketRequestBody: CreateTicketRequestBody,
  options?: RequestInit,
): Promise<createTicketControllerExecuteResponse> => {
  const res = await fetch(getCreateTicketControllerExecuteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTicketRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTicketControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createTicketControllerExecuteResponse;
};

export const getCreateTicketControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTicketControllerExecute>>,
    TError,
    { data: CreateTicketRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTicketControllerExecute>>,
  TError,
  { data: CreateTicketRequestBody },
  TContext
> => {
  const mutationKey = ["createTicketControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTicketControllerExecute>>,
    { data: CreateTicketRequestBody }
  > = (props) => {
    const { data } = props ?? {};

    return createTicketControllerExecute(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTicketControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTicketControllerExecute>>
>;
export type CreateTicketControllerExecuteMutationBody = CreateTicketRequestBody;
export type CreateTicketControllerExecuteMutationError = ApiError;

/**
 * @summary Create a new ticket
 */
export const useCreateTicketControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTicketControllerExecute>>,
      TError,
      { data: CreateTicketRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTicketControllerExecute>>,
  TError,
  { data: CreateTicketRequestBody },
  TContext
> => {
  const mutationOptions = getCreateTicketControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Retrieve all tickets accessible to the logged user
 * @summary List tickets
 */
export type listTicketsByFilterControllerExecuteResponse200 = {
  data: ResponseTicketPaginated;
  status: 200;
};

export type listTicketsByFilterControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type listTicketsByFilterControllerExecuteResponseSuccess =
  listTicketsByFilterControllerExecuteResponse200 & {
    headers: Headers;
  };
export type listTicketsByFilterControllerExecuteResponseError =
  listTicketsByFilterControllerExecuteResponse500 & {
    headers: Headers;
  };

export type listTicketsByFilterControllerExecuteResponse =
  | listTicketsByFilterControllerExecuteResponseSuccess
  | listTicketsByFilterControllerExecuteResponseError;

export const getListTicketsByFilterControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/tickets`;
};

export const listTicketsByFilterControllerExecute = async (
  options?: RequestInit,
): Promise<listTicketsByFilterControllerExecuteResponse> => {
  const res = await fetch(getListTicketsByFilterControllerExecuteUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTicketsByFilterControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listTicketsByFilterControllerExecuteResponse;
};

export const getListTicketsByFilterControllerExecuteQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/tickets`] as const;
};

export const getListTicketsByFilterControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTicketsByFilterControllerExecuteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>
  > = ({ signal }) => listTicketsByFilterControllerExecute({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTicketsByFilterControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>
>;
export type ListTicketsByFilterControllerExecuteQueryError = ApiError;

export function useListTicketsByFilterControllerExecute<
  TData = Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTicketsByFilterControllerExecute<
  TData = Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTicketsByFilterControllerExecute<
  TData = Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List tickets
 */

export function useListTicketsByFilterControllerExecute<
  TData = Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTicketsByFilterControllerExecute>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTicketsByFilterControllerExecuteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieve a ticket by their unique ID
 * @summary Get ticket by ID
 */
export type getTicketByIdControllerExecuteResponse200 = {
  data: ResponseTicket;
  status: 200;
};

export type getTicketByIdControllerExecuteResponse204 = {
  data: void;
  status: 204;
};

export type getTicketByIdControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type getTicketByIdControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getTicketByIdControllerExecuteResponseSuccess = (
  | getTicketByIdControllerExecuteResponse200
  | getTicketByIdControllerExecuteResponse204
) & {
  headers: Headers;
};
export type getTicketByIdControllerExecuteResponseError = (
  | getTicketByIdControllerExecuteResponse400
  | getTicketByIdControllerExecuteResponse500
) & {
  headers: Headers;
};

export type getTicketByIdControllerExecuteResponse =
  | getTicketByIdControllerExecuteResponseSuccess
  | getTicketByIdControllerExecuteResponseError;

export const getGetTicketByIdControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/tickets/${id}`;
};

export const getTicketByIdControllerExecute = async (
  id: unknown,
  options?: RequestInit,
): Promise<getTicketByIdControllerExecuteResponse> => {
  const res = await fetch(getGetTicketByIdControllerExecuteUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTicketByIdControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getTicketByIdControllerExecuteResponse;
};

export const getGetTicketByIdControllerExecuteQueryKey = (id?: unknown) => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/tickets/${id}`] as const;
};

export const getGetTicketByIdControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTicketByIdControllerExecuteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>> = ({
    signal,
  }) => getTicketByIdControllerExecute(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTicketByIdControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTicketByIdControllerExecute>>
>;
export type GetTicketByIdControllerExecuteQueryError = ApiError;

export function useGetTicketByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getTicketByIdControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTicketByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getTicketByIdControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTicketByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get ticket by ID
 */

export function useGetTicketByIdControllerExecute<
  TData = Awaited<ReturnType<typeof getTicketByIdControllerExecute>>,
  TError = ApiError,
>(
  id: unknown,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTicketByIdControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTicketByIdControllerExecuteQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a ticket's details by their unique ID
 * @summary Update ticket by ID
 */
export type updateTicketControllerExecuteResponse200 = {
  data: ResponseTicket;
  status: 200;
};

export type updateTicketControllerExecuteResponse204 = {
  data: void;
  status: 204;
};

export type updateTicketControllerExecuteResponse400 = {
  data: ApiError;
  status: 400;
};

export type updateTicketControllerExecuteResponse404 = {
  data: void;
  status: 404;
};

export type updateTicketControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type updateTicketControllerExecuteResponseSuccess = (
  | updateTicketControllerExecuteResponse200
  | updateTicketControllerExecuteResponse204
) & {
  headers: Headers;
};
export type updateTicketControllerExecuteResponseError = (
  | updateTicketControllerExecuteResponse400
  | updateTicketControllerExecuteResponse404
  | updateTicketControllerExecuteResponse500
) & {
  headers: Headers;
};

export type updateTicketControllerExecuteResponse =
  | updateTicketControllerExecuteResponseSuccess
  | updateTicketControllerExecuteResponseError;

export const getUpdateTicketControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/tickets/${id}`;
};

export const updateTicketControllerExecute = async (
  id: unknown,
  updateTicketRequestBody: UpdateTicketRequestBody,
  options?: RequestInit,
): Promise<updateTicketControllerExecuteResponse> => {
  const res = await fetch(getUpdateTicketControllerExecuteUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTicketRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTicketControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateTicketControllerExecuteResponse;
};

export const getUpdateTicketControllerExecuteMutationOptions = <
  TError = ApiError | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTicketControllerExecute>>,
    TError,
    { id: unknown; data: UpdateTicketRequestBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTicketControllerExecute>>,
  TError,
  { id: unknown; data: UpdateTicketRequestBody },
  TContext
> => {
  const mutationKey = ["updateTicketControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTicketControllerExecute>>,
    { id: unknown; data: UpdateTicketRequestBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTicketControllerExecute(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTicketControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTicketControllerExecute>>
>;
export type UpdateTicketControllerExecuteMutationBody = UpdateTicketRequestBody;
export type UpdateTicketControllerExecuteMutationError = ApiError | void;

/**
 * @summary Update ticket by ID
 */
export const useUpdateTicketControllerExecute = <TError = ApiError | void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTicketControllerExecute>>,
      TError,
      { id: unknown; data: UpdateTicketRequestBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTicketControllerExecute>>,
  TError,
  { id: unknown; data: UpdateTicketRequestBody },
  TContext
> => {
  const mutationOptions = getUpdateTicketControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * The ticket ID must be provided
 * @summary Performs a soft delete operation
 */
export type deleteTicketControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type deleteTicketControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type deleteTicketControllerExecuteResponseSuccess =
  deleteTicketControllerExecuteResponse200 & {
    headers: Headers;
  };
export type deleteTicketControllerExecuteResponseError =
  deleteTicketControllerExecuteResponse500 & {
    headers: Headers;
  };

export type deleteTicketControllerExecuteResponse =
  | deleteTicketControllerExecuteResponseSuccess
  | deleteTicketControllerExecuteResponseError;

export const getDeleteTicketControllerExecuteUrl = (id: unknown) => {
  return `https://nortus-challenge.api.stage.loomi.com.br/tickets/${id}`;
};

export const deleteTicketControllerExecute = async (
  id: unknown,
  options?: RequestInit,
): Promise<deleteTicketControllerExecuteResponse> => {
  const res = await fetch(getDeleteTicketControllerExecuteUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteTicketControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteTicketControllerExecuteResponse;
};

export const getDeleteTicketControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTicketControllerExecute>>,
    TError,
    { id: unknown },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTicketControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationKey = ["deleteTicketControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTicketControllerExecute>>,
    { id: unknown }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTicketControllerExecute(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTicketControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTicketControllerExecute>>
>;

export type DeleteTicketControllerExecuteMutationError = ApiError;

/**
 * @summary Performs a soft delete operation
 */
export const useDeleteTicketControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTicketControllerExecute>>,
      TError,
      { id: unknown },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTicketControllerExecute>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationOptions = getDeleteTicketControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Reset and populate tickets table with data from JSON files
 * @summary Seed tickets
 */
export type seedTicketsControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type seedTicketsControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type seedTicketsControllerExecuteResponseSuccess =
  seedTicketsControllerExecuteResponse200 & {
    headers: Headers;
  };
export type seedTicketsControllerExecuteResponseError = seedTicketsControllerExecuteResponse500 & {
  headers: Headers;
};

export type seedTicketsControllerExecuteResponse =
  | seedTicketsControllerExecuteResponseSuccess
  | seedTicketsControllerExecuteResponseError;

export const getSeedTicketsControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/seed/tickets`;
};

export const seedTicketsControllerExecute = async (
  options?: RequestInit,
): Promise<seedTicketsControllerExecuteResponse> => {
  const res = await fetch(getSeedTicketsControllerExecuteUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: seedTicketsControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as seedTicketsControllerExecuteResponse;
};

export const getSeedTicketsControllerExecuteMutationOptions = <
  TError = ApiError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof seedTicketsControllerExecute>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof seedTicketsControllerExecute>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["seedTicketsControllerExecute"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof seedTicketsControllerExecute>>,
    void
  > = () => {
    return seedTicketsControllerExecute(fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SeedTicketsControllerExecuteMutationResult = NonNullable<
  Awaited<ReturnType<typeof seedTicketsControllerExecute>>
>;

export type SeedTicketsControllerExecuteMutationError = ApiError;

/**
 * @summary Seed tickets
 */
export const useSeedTicketsControllerExecute = <TError = ApiError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof seedTicketsControllerExecute>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof seedTicketsControllerExecute>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSeedTicketsControllerExecuteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Retrieve mapa locations data from locations.json file
 * @summary Get mapa locations data
 */
export type getMapaControllerExecuteResponse200 = {
  data: void;
  status: 200;
};

export type getMapaControllerExecuteResponse500 = {
  data: ApiError;
  status: 500;
};

export type getMapaControllerExecuteResponseSuccess = getMapaControllerExecuteResponse200 & {
  headers: Headers;
};
export type getMapaControllerExecuteResponseError = getMapaControllerExecuteResponse500 & {
  headers: Headers;
};

export type getMapaControllerExecuteResponse =
  | getMapaControllerExecuteResponseSuccess
  | getMapaControllerExecuteResponseError;

export const getGetMapaControllerExecuteUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/map/locations`;
};

export const getMapaControllerExecute = async (
  options?: RequestInit,
): Promise<getMapaControllerExecuteResponse> => {
  const res = await fetch(getGetMapaControllerExecuteUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapaControllerExecuteResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMapaControllerExecuteResponse;
};

export const getGetMapaControllerExecuteQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/map/locations`] as const;
};

export const getGetMapaControllerExecuteQueryOptions = <
  TData = Awaited<ReturnType<typeof getMapaControllerExecute>>,
  TError = ApiError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMapaControllerExecute>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMapaControllerExecuteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapaControllerExecute>>> = ({
    signal,
  }) => getMapaControllerExecute({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMapaControllerExecute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMapaControllerExecuteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMapaControllerExecute>>
>;
export type GetMapaControllerExecuteQueryError = ApiError;

export function useGetMapaControllerExecute<
  TData = Awaited<ReturnType<typeof getMapaControllerExecute>>,
  TError = ApiError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMapaControllerExecute>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapaControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getMapaControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMapaControllerExecute<
  TData = Awaited<ReturnType<typeof getMapaControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMapaControllerExecute>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapaControllerExecute>>,
          TError,
          Awaited<ReturnType<typeof getMapaControllerExecute>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMapaControllerExecute<
  TData = Awaited<ReturnType<typeof getMapaControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMapaControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get mapa locations data
 */

export function useGetMapaControllerExecute<
  TData = Awaited<ReturnType<typeof getMapaControllerExecute>>,
  TError = ApiError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMapaControllerExecute>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMapaControllerExecuteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type prometheusControllerGetMetricsResponse200 = {
  data: void;
  status: 200;
};

export type prometheusControllerGetMetricsResponseSuccess =
  prometheusControllerGetMetricsResponse200 & {
    headers: Headers;
  };
export type prometheusControllerGetMetricsResponse = prometheusControllerGetMetricsResponseSuccess;

export const getPrometheusControllerGetMetricsUrl = () => {
  return `https://nortus-challenge.api.stage.loomi.com.br/metrics`;
};

export const prometheusControllerGetMetrics = async (
  options?: RequestInit,
): Promise<prometheusControllerGetMetricsResponse> => {
  const res = await fetch(getPrometheusControllerGetMetricsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: prometheusControllerGetMetricsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as prometheusControllerGetMetricsResponse;
};

export const getPrometheusControllerGetMetricsQueryKey = () => {
  return [`https://nortus-challenge.api.stage.loomi.com.br/metrics`] as const;
};

export const getPrometheusControllerGetMetricsQueryOptions = <
  TData = Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrometheusControllerGetMetricsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>> = ({
    signal,
  }) => prometheusControllerGetMetrics({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrometheusControllerGetMetricsQueryResult = NonNullable<
  Awaited<ReturnType<typeof prometheusControllerGetMetrics>>
>;
export type PrometheusControllerGetMetricsQueryError = unknown;

export function usePrometheusControllerGetMetrics<
  TData = Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerGetMetrics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrometheusControllerGetMetrics<
  TData = Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerGetMetrics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrometheusControllerGetMetrics<
  TData = Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePrometheusControllerGetMetrics<
  TData = Awaited<ReturnType<typeof prometheusControllerGetMetrics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerGetMetrics>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrometheusControllerGetMetricsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
