/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { CreateTicketRequestBodyPriority } from "./createTicketRequestBodyPriority";
import type { CreateTicketRequestBodyStatus } from "./createTicketRequestBodyStatus";

export interface CreateTicketRequestBody {
  /** Ticket ID */
  ticketId: string;
  /** Priority */
  priority: CreateTicketRequestBodyPriority;
  /** Client name */
  client: string;
  /** Client email */
  email: string;
  /** Ticket subject */
  subject: string;
  /** Status */
  status: CreateTicketRequestBodyStatus;
  /** Responsible person */
  responsible: string;
}
