/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

export interface CreateUserRequestBody {
  /** User name */
  name: string;
  /** User password */
  password: string;
  /** User email */
  email: string;
  /**
   * User challenge level
   * @minimum 1
   */
  challengeLevel?: number;
}
