/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Priority
 */
export type ResponseTicketPriority =
  (typeof ResponseTicketPriority)[keyof typeof ResponseTicketPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseTicketPriority = {
  Urgente: "Urgente",
  Média: "Média",
  Baixa: "Baixa",
  Alta: "Alta",
} as const;
