/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

/**
 * User state
 */
export type ResponseUserState = (typeof ResponseUserState)[keyof typeof ResponseUserState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseUserState = {
  CONFIRMED: "CONFIRMED",
  PENDING_CONFIRMATION: "PENDING_CONFIRMATION",
} as const;
