/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { ResponseTicketPriority } from "./responseTicketPriority";
import type { ResponseTicketStatus } from "./responseTicketStatus";

export interface ResponseTicket {
  /** Ticket ID */
  id: string;
  /** Ticket ID */
  ticketId: string;
  /** Priority */
  priority: ResponseTicketPriority;
  /** Client name */
  client: string;
  /** Client email */
  email: string;
  /** Ticket subject */
  subject: string;
  /** Status */
  status: ResponseTicketStatus;
  /** Responsible person */
  responsible: string;
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt: string;
}
