/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { ResponseToUpdateUserForgotPasswordState } from "./responseToUpdateUserForgotPasswordState";

export interface ResponseToUpdateUserForgotPassword {
  /** User access_token */
  access_token: string;
  state: ResponseToUpdateUserForgotPasswordState;
}
