/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { ResponseTicket } from "./responseTicket";

export interface ResponseTicketPaginated {
  data: ResponseTicket[];
  /** Data total entries */
  total: number;
  /** Data total listed */
  listed: number;
}
