/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Status
 */
export type ResponseTicketStatus = (typeof ResponseTicketStatus)[keyof typeof ResponseTicketStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseTicketStatus = {
  Aberto: "Aberto",
  Em_andamento: "Em andamento",
  Fechado: "Fechado",
} as const;
