/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

export type ResponseToUpdateUserForgotPasswordState =
  (typeof ResponseToUpdateUserForgotPasswordState)[keyof typeof ResponseToUpdateUserForgotPasswordState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseToUpdateUserForgotPasswordState = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
} as const;
