/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateUserForgotPasswordRequestBody {
  /** User forgot password id */
  id: string;
  /**
   * Code to update password
   * @minLength 5
   */
  code: string;
  /** New password */
  new_password: string;
}
