/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateUserRequestBodyState } from "./updateUserRequestBodyState";

export interface UpdateUserRequestBody {
  /** User email */
  email?: string;
  /** User name */
  name?: string;
  /** User state */
  state?: UpdateUserRequestBodyState;
}
