/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NODE-LEAP API
 * Nortus Challenge is a node boilerplate that follows best practicles of software design and agile.
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateTicketRequestBodyPriority } from "./updateTicketRequestBodyPriority";
import type { UpdateTicketRequestBodyStatus } from "./updateTicketRequestBodyStatus";

export interface UpdateTicketRequestBody {
  /** Priority */
  priority?: UpdateTicketRequestBodyPriority;
  /** Client name */
  client?: string;
  /** Client email */
  email?: string;
  /** Ticket subject */
  subject?: string;
  /** Status */
  status?: UpdateTicketRequestBodyStatus;
  /** Responsible person */
  responsible?: string;
}
